apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d8ln
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-d8ln@sha256:d424ccf323bc4bfa73acfd8d7cf5531eb41068898c54a7d1b56403fd2eedd56f
        name: my-nodejs
        resources: {}
status: {}
